project:
  type: website
  preview:
    port: 4000

website:
  title: "exemplo_blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: quartz
    css: styles.css

editor: visual

lang: pt